baseURL = 'https://praneethgunas.github.io/whoami/'
languageCode = 'en-us'
title = 'Praneeth G'
theme = 'nightfall'

[params]
    user = "whoami"
    hostname = "praneeth"
    sitedescription = 'Security researcher and software engineer pursuing MS in Computer Science at Virginia Tech'
    published = false
    readingTime = false
    footerHtml = 'üìç Arlington, VA, USA Research Assistant at <a href="https://cyberinitiative.org/" class="footerLink">Commonwealth Cyber Initiative</a> in <a href="https://vt.edu/" class="footerLink">Virginia Tech</a>'

    [params.author]
        name = "Hi üëã, I'm Praneeth"
        email = "inboxpraneeth@gmail.com"

    [[params.social]]
        key = 1
        name = "github"
        url = "https://github.com/PraneethGunas"
        target = "_blank"
        aria = "Praneeth GitHub" # Define the aria label for accessibility like page reader - this is better for your SEO

    [[params.social]]
        key = 2
        name = "twitter"
        target = "_blank"
        url = "https://x.com/PraneethGunas"

    [[params.social]]
        key = 3
        name = "linkedin"
        url = "https://www.linkedin.com/in/praneeth-g/"
        target = "_blank"
        rel = "me"  # You can also add rel to social link

    [[params.social]]
        key = 4
        name = "email"
        target = "_blank"
        url = "mailto:inboxpraneeth@gmail.com"

    [[params.social]]
        key = 5
        name = "resume"
        url = "https://praneeth-resume.tiiny.site"
        target = "_blank"
    

    [menu]
        [[menu.header]]
            name = "about"
            weight = 1
            url = "/about/"
        
        [[menu.header]]
            name = "curriculum"
            weight = 1
            url = "/curriculum/"

        [[menu.header]]
            name = "projects"
            weight = 1
            url = "/projects/"
